name: Sync
on: workflow_dispatch
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Sync
        run: |
          git remote add upstream https://github.com/nealmanaktola/sdk-test.git
          git fetch upstream
          git config --global user.name github.actions
          git config --global user.email github-actions@github.com
          git merge --allow-unrelated-histories --no-commit --strategy-option theirs upstream/master
          contents="$(jq '.name = "sdk-test-e" | .repository = "https://github.com/nealmanaktola/sdk-test-e.git"' package.json)" && echo "${contents}" > package.json
          git add package.json
          git -c core.editor=/bin/true merge --continue
          git push